### ISSUE TITLE
Autoenrollment upon activity view not working

### ISSUE THREAD

**Issue by federicama** [eugeneventer/moodle-enrol_auto#1]
Hello, first of all thanks for the plugin! It is really helpful for us. :)
When I set up the autoenrollment with the course view criterium it perfectly works: users enter the course and get enrolled in it.
Unluckily I found an issue with the autoenrollment upon activity/resource view: even if the users have the link to the specific activity (and not the all course), they cannot visualize it because they are not enrolled. 
Is there something that I am missing in the settings?

Thanks for your attention!

**Comment by eugeneventer** [comment]
Hi there, you need to Guest access in your course ;)
