### ISSUE TITLE
Missing editenrolment.php file

### ISSUE THREAD

**Issue by wmrandth** [eugeneventer/moodle-enrol_auto#4]
In 3.1.2 latest I am getting a 'File not found' error when trying to manually unenrol a user as Teacher in the usual way.

It is looking for the file enrol/auto/editenrolment.php which is not in the install package or git. 

This file is referenced and called from line 330 of lib.php at: 

`$url = new moodle_url('/enrol/auto/editenrolment.php', $params);
`

**Comment by eugeneventer** [comment]
Thanks for the bug report @wmrandth ;) I've now fixed this in the master branch and will shortly be releasing it to the supported versions.

Regards,
Eugene.

**Comment by wmrandth** [comment]
Sweet, thanks for the super quick fix :)

Randy
--
Moodle Ronin :: Randy Thornton Consulting
503.490.4485 :: randy@thornedu.com
